name: Trigger yuhang.ch Deployment

on:
  push:
    branches:
      - main 

jobs:
  trigger_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deployment via webhook
      run: |
        curl -X POST https://api.github.com/repos/yuhangch/yuhang.ch/dispatches \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -H "Authorization: Bearer ${{ secrets.CONTENT_DEPLOY_TOKEN }}" \
        -d '{"event_type":"content_update"}'
